const Difficulty = [
    { 
        name: "Goomba", 
        nickname: "Very Easy",
        icon: "goomba.gif",
        css: "--very-easy",
        dist: [ 
            1, 1, 1, 1, 1,
            1, 1, 1, 1, 1,
            1, 1, 1, 1, 1,
            1, 1, 2, 2, 2,
            2, 2, 2, 3, 3,
         ],
         type: "difficulty",
    },
    { 
        name: "Koopa", 
        nickname: "Easy",
        icon: "koopa.gif",
        css: "--easy",
        dist: [ 
            1, 1, 1, 1, 1,
            1, 1, 2, 2, 2,
            2, 2, 2, 2, 2,
            2, 3, 3, 3, 3,
            3, 3, 3, 3, 4,
         ],
         type: "difficulty",
    },
    { 
        name: "Hammer Bro", 
        nickname: "Normal",
        icon: "hammer.gif",
        css: "--normal",
        dist: [ 
            1, 1, 1, 1, 1,
            2, 2, 2, 2, 2,
            2, 2, 3, 3, 3,
            3, 3, 3, 3, 3,
            3, 3, 4, 4, 5,
         ],
         type: "difficulty",
    },
    { 
        name: "Chargin' Chuck", 
        nickname: "Hard",
        icon: "chuck.gif",
        css: "--hard",
        dist: [ 
            1, 1, 1, 1, 2,
            2, 2, 2, 2, 3,
            3, 3, 3, 3, 3,
            3, 3, 4, 4, 4,
            4, 5, 5, 5, 6,
         ],
         type: "difficulty",
    },
    { 
        name: "Magikoopa", 
        nickname: "Very Hard",
        icon: "magikoopa.gif",
        css: "--very-hard",
        dist: [ 
            1, 1, 1, 2, 2,
            2, 2, 3, 3, 3, 
            3, 3, 3, 4, 4,
            4, 4, 4, 5, 5,
            5, 5, 6, 6, 7,
         ],
         type: "difficulty",
    },
    { 
        name: "Reznor", 
        nickname: "Extreme",
        icon: "reznor.gif",
        css: "--extreme",
        dist: [ 
            1, 2, 2, 3, 3,
            3, 3, 4, 4, 4,
            4, 4, 4, 4, 5,
            5, 5, 5, 5, 6,
            6, 4, 4, 7, 7,
         ],
         type: "difficulty",
    },
    { 
        name: "Bowser", 
        nickname: "Absolutely Insane",
        icon: "bowser.gif",
        css: "--insane",
        dist: [ 
            1, 3, 3, 3, 4,
            4, 4, 4, 4, 4,
            5, 5, 5, 5, 5,
            6, 6, 6, 6, 6, 
            6, 6, 7, 7, 7,
         ],
         type: "difficulty",
    },
    {
        name: "Balanced",
        nickname: "As All Things Should Be",
        icon: "balanced.gif",
        css: "--balanced",
        dist: [
            1, 1, 1, 1, 2,
            2, 2, 2, 3, 3,
            3, 3, 4, 4, 4,
            4, 5, 5, 5, 5,
            6, 6, 6, 6, 7,
        ],
        type: "difficulty",
    },
    {
        name: "Random Difficulty",
        nickname: "For the Indecisive",
        icon: "random.gif",
        css: "--random",
        dist: [],
        type: "random",
    },
    {
        name: "Pure Random",
        nickname: "Let's Get Crazy!!!",
        icon: "chaos.gif",
        css: "--all-random",
        dist: [],
        type: "all-random",
    }
];